# Copyright(c) 2023 Felipe Contreras

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
##########################################################################################
##########################################################################################
##################################  AUTHOR README  #######################################
##########################################################################################
##########################################################################################

# @FILE NAME: LAAT_and_MBMS_example.py
#
# @BRIEF DESCRIPTION: Example of how to run LAAT and/or MBMS.
# 
# @RELASE: Felipe Contreras (f.i.contreras.sepulveda@rug.nl), 2023-02-21, version 1.0.0
#
# @VERSION: Felipe Contreras (f.i.contreras.sepulveda@rug.nl), 03-11-2023, version 1.2.0
#
# @INPUT: 2 input files are necessary.
#         First: the data .cvs file storage under the code parameter 'data'. With rows representing 
#         the points and the columns representing the position X, Y and Z, respectively. 
#         Second: a data file .cvs storage under the code parameter 'manifold_points'. The file 
#         must contain 1 single column with n number of rows. Every row represent the number of
#         particles in every submanifold. For mor information about the input example read
#         the script 'Polynomial3DManifold_with_noise.py'  
#
# @OUTPUT: At maximum of four .cvs files and five .png images.    
#
# @PREREQUISITES: 
#
# @LONG DESCRIPTION: 
#
# The script generate run LAAT and MBMS using by default an example generated by the script
# 'Polynomial3DManifold_with_noise.py'. After running LAAT and MBMS the code export the 
# results in .cvs files and .png images. 
# 
# The user is available to change different parameters, but LAAT is still parameter dependent
# on the type of data particularly in the parameter 'LAAT_neighbdradii', and 'LAAT_th_neighb'. 
# Both are related each other and depends on the volume of the data. Moreover, the parameters
# which manage the total amount of pheromone delivered ('LAAT_numberOfAntsX', 'LAAT_numberOfIterations',
# 'LAAT_numberOfSteps', etc) they depends on the number of data points.
#
# @RATIONALES:
#  - [a] This script is an example of a particular situation given by the script 'Polynomial3DManifold_with_noise.py'.
#        For this reason, this code is not intended to run any other data set properly but can be used as a template. 
#
# @NOTES:
#  - [a] 
#
# @FUTURE WORKS:
#  - [a] 



##########################################################################################
##########################################################################################
######################################  LIBRARIES  #######################################
##########################################################################################
##########################################################################################

import pandas as pd
import numpy as np
import LAAT_MBMS

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


##########################################################################################
##########################################################################################
######################################  INPUT DATA  ######################################
##########################################################################################
##########################################################################################


data = pd.read_csv('../Synthetic_Manifold_1.csv', header=None).to_numpy()
  
#LAAT parameters
LAAT_numberOfAnts = 5**3 # Number of Ants
LAAT_numberOfIterations = 100 # Number of epochs
LAAT_numberOfSteps = 2500 # Number of steps of every ant between epochs

LAAT_pso_number_particles = 30											#Number of radii to test. The value must be >= 2 if LAAT_dynamic_radius_actived is equal to 1
LAAT_pso_min_radii = 1.0														#Min radii
LAAT_pso_max_radii = 3.5														#Max radii. In case of No dyanamic radius, this value is used as the fix radius
LAAT_dynamic_radius_actived = 0										#0 = No dynamic radius. 1 = dynamic radius 

#	NOTE:	If you activate the the dynamic radius ("dynamic radius active = 1"), 
# 			then you will get better results but it will cost more time and more memory

LAAT_th_neighb = 9 # Threshold in the amount of neighbors of the points for the pheromone deliver
LAAT_kappa = 0.8  # Coeffient paramter  given the amount of importance to reinforment or alignment

LAAT_numberofthreads = 4  # Number of threds (cores) used to run the script. 



pheromone = LAAT_MBMS.LAAT(	data,
                            LAAT_numberOfAnts,
                            LAAT_numberOfIterations,
                            LAAT_numberOfSteps,
														LAAT_pso_number_particles,
														LAAT_pso_min_radii,
														LAAT_pso_max_radii,
														LAAT_dynamic_radius_actived,
                            LAAT_th_neighb,
                            LAAT_kappa,
                            LAAT_numberofthreads)  

##########################################################################################
##########################################################################################
#################################  EXPORTING DATA  #######################################
##########################################################################################
##########################################################################################
print("EXPORTING")

np.savetxt("../Output/LAAT_output_pheromone.csv", pheromone, delimiter=',', fmt = '%5.8f')



