#### USE THE CHARACTER '#' TO ADD YOUR COMMENTS. 

### The order of appearance of the parameters is not relevant, but the variable
### type it is. 

### If a parameter is ommited or commented, it will be equal to the default value (see the terminal output while LAAT is running to see the paramters used)

input_data_file = ../Synthetic_Manifold_1.csv	#Data file address
ouptut_file_address = ../Output/LAAT_output_pheromone.csv	#Output file address

numberOfAnts = 125														#Number of ants
numberOfIterations = 100 											#Number of Epochs
numberOfSteps = 2500													#Number of jump steps per ant per epoch

pso_number_particles = 30											#Number of radii to test
pso_min_radii = 1.0														#Min radii
pso_max_radii = 3.5														#Max radii. In case of No dyanamic radius, this value is used as the fix radius
dynamic_radius_actived = 0										#0 = No dynamic radius. 1 = dynamic radius 

th_neighb = 5																	#th_neighb + 1 = Minimum number of neighbours per neighbourhood 
kappa = 0.8																		#Value of the reinforcement. kappa*E + (1-kappa)*F;	E = Preference, F = Pheromone accumulated

numberofthreads = 16														#Number of threads used

#	NOTE:	If you activate the the dynamic radius ("dynamic radius active = 1"), 
# 			then you will get better results but it will cost more time and more memory