# Copyright(c) 2023 Felipe Contreras

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
##########################################################################################
##########################################################################################
##################################  AUTHOR README  #######################################
##########################################################################################
##########################################################################################

# @FILE NAME: LAAT_and_MBMS_example.py
#
# @BRIEF DESCRIPTION: Example of how to run LAAT and/or MBMS.
# 
# @RELASE: Felipe Contreras (f.i.contreras.sepulveda@rug.nl), 2023-02-21, version 1.0.0
#
# @VERSION: Felipe Contreras (f.i.contreras.sepulveda@rug.nl), 2023-02-24, version 1.0.3
#
# @INPUT: 2 input files are necessary.
#         First: the data .cvs file storage under the code parameter 'data'. With rows representing 
#         the points and the columns representing the position X, Y and Z, respectively. 
#         Second: a data file .cvs storage under the code parameter 'manifold_points'. The file 
#         must contain 1 single column with n number of rows. Every row represent the number of
#         particles in every submanifold. For mor information about the input example read
#         the script 'Polynomial3DManifold_with_noise.py'  
#
# @OUTPUT: At maximum of four .cvs files and five .png images.    
#
# @PREREQUISITES: 
#
# @LONG DESCRIPTION: 
#
# The script generate run LAAT and MBMS using by default an example generated by the script
# 'Polynomial3DManifold_with_noise.py'. After running LAAT and MBMS the code export the 
# results in .cvs files and .png images. 
# 
# The user is available to change different parameters, but LAAT is still parameter dependent
# on the type of data particularly in the parameter 'LAAT_neighbdradii', and 'LAAT_th_neighb'. 
# Both are related each other and depends on the volume of the data. Moreover, the parameters
# which manage the total amount of pheromone delivered ('LAAT_numberOfAntsX', 'LAAT_numberOfIterations',
# 'LAAT_numberOfSteps', etc) they depends on the number of data points.
#
# @RATIONALES:
#  - [a] This script is an example of a particular situation given by the script 'Polynomial3DManifold_with_noise.py'.
#        For this reason, this code is not intended to run any other data set properly but can be used as a template. 
#
# @NOTES:
#  - [a] 
#
# @FUTURE WORKS:
#  - [a] 



##########################################################################################
##########################################################################################
######################################  LIBRARIES  #######################################
##########################################################################################
##########################################################################################

import pandas as pd
import numpy as np
import LAAT_MBMS



##########################################################################################
##########################################################################################
######################################  INPUT DATA  ######################################
##########################################################################################
##########################################################################################


data = np.loadtxt('../Output/LAAT_output_selected_data.csv', delimiter=',')


# MBMS Parameters
MBMS_iter = 3	  # Number of times the points are picked up and moved closer to the center
MBMS_radius = 1.5 # This radius must  be biger or equal than the radius used on LAAT
MBMS_sigma = 1.5
MBMS_k = 9	# number of nearest neighbours used to estimate the local tangent space (similar to LAAT_th_neighb )




# run the MBMS algorithm on the selected data points with the specified
# hyper-parameter values, store the resulting shifted data
MBMS_data = LAAT_MBMS.MBMS(data,
                        iter = MBMS_iter,
                        radius = MBMS_radius,
                        sigma = MBMS_sigma,
                        k = MBMS_k)
                             


##########################################################################################
##########################################################################################
#################################  EXPORTING DATA  #######################################
##########################################################################################
##########################################################################################
print("EXPORTING")

np.savetxt("../Output/MBMS_output.csv", MBMS_data, delimiter=',', fmt = '%5.8f')

